### ISSUE TITLE
Version 1.0.0 missing from npm?

### ISSUE THREAD

**Issue by joekiller** [lucasfeliciano/grunt-tunnelstack#1]
Seems like version 1.0.0 disappeared recently from NPM: https://www.npmjs.com/package/grunt-tunnelstack

```
npm ERR! notarget No compatible version found: grunt-tunnelstack@'>=1.0.0-0 <2.0.0-0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

https://registry.npmjs.org/grunt-tunnelstack/1.0.0 lists not found.

**Comment by ianwremmel** [comment]
Running into this as well

**Comment by lucasfeliciano** [comment]
Hey guys,

Sorry for the delay.

To respect browserstack's nomenclature this module is deprecated.

It was added to browserstack's  [official documentation](http://browserstack.com/automate/integrations) as [grunt-localstack](https://github.com/lucasfeliciano/grunt-localstack) please change the dependency name in your project.
